Refactor EventCall to store Event Declaration
CertiKProject/slither-certik pull request #3
Opened 2022-05-31 20:19 UTC by EULIR

Previously an EventCall only store the name of the event (as a string), which isn't ideal for a lot of purpose. Now it stores the event object, as it should be.

2022-05-31 20:36 UTC, duckki commented
please rebase on origin/certik. I just squash merged PR#2.

2022-05-31 21:37 UTC, duckki requested changes

2022-05-31 21:37 UTC, duckki commented on slither/slithir/operations/event_call.py
>          # todo add instance of the Event
Remove the "todo" comment. The destination is an instance of Event class.

2022-05-31 21:43 UTC, EULIR commented on slither/slithir/operations/event_call.py
>          # todo add instance of the Event
Resolved.

2022-06-01 01:27 UTC, duckki requested changes
Please rebase on top of my new commit `36291cd91e08c6f8edcbaecf30790804edc852aa`. It fixes a crash.
Once rebased, I'll run the detector over a number of projects to get the results.

2022-06-01 15:05 UTC, duckki commented
It looks good. But, I'll do a test run.

2022-06-01 20:05 UTC, duckki requested changes
I noticed one project lost a finding.

2022-06-01 20:05 UTC, duckki commented on slither/slithir/convert.py
> +            event_sym = resolve_event(ins.ori.variable_right, contract)
Use `str(ins.ori.variable_right)`, otherwise the resolve_event will try to compare events by reference, not by name.

2022-06-01 20:05 UTC, duckki commented on slither/slithir/convert.py
> +            event_sym = resolve_event(ins.ori.variable_right, ins.ori.variable_left)
Same here.

2022-06-01 22:07 UTC, EULIR commented on slither/slithir/convert.py
> +            event_sym = resolve_event(ins.ori.variable_right, contract)
resolved.

2022-06-02 01:46 UTC, duckki commented
It turned out to be a non-determinism where a divide-before-multiple finding is lost sometimes.
I filed https://github.com/CertiKProject/slither-task/issues/79 for that.

2022-06-02 01:47 UTC, duckki approved these changes
Looks good.
I tried 200 projects and they ran successfully.
No changes in findings. Except the non-determinism issue.

2022-06-02 01:48 UTC, merged