feat: add push operation, include push operation in generated code
CertiKProject/slither-certik pull request #39
Opened 2023-04-24 01:38 UTC by kevinclancy

### Notes

The IR for performing a `push` method for dynamic arrays currently uses an `Assign` operation to add the new element to the array. When the left-hand side of an `Assign` is a storage location, a deep copy is performed. Instead of deep copying, we want to allocate a new element in storage. No IR operation currently does this, so this PR adds a new operation called `Push`. 

In addition to allocating a value and adding it to the array, the `Push` operation has an lvalue which is used as the return value for the `push` method. This allows us to access the newly allocated element as an individual instead of using an `Item` abstract value, which conflates the newly allocated element with all the other elements of the array.

### Testing
* A companion PR in `slither-task` will extend DataflowStateMachine to handle Push operations. Testing should be done there.

### Related Issue
https://github.com/CertiKProject/slither-task/issues/461

2023-04-25 00:11 UTC, duckki commented
IRs generated originally:
```
// Step 1 - incrementing the length
 REF_1 -> LENGTH s
 TMP_1(uint256) := REF_1(uint256)
 TMP_2(uint256) = TMP_1 (c)+ 1
 REF_1 (->s) := TMP_2(uint256)

// Step 2 - delete or deep-copy to the new object
 REF_2 -> s[TMP_1]  // This is a source imprecision.
 // missing `initialization` or `assign` to REF_2 (depending on `push()` or `push(x)`)
```

Here, we want to handle both `push()` and `push(x)` consistently. I think the critical point is `REF_2 -> s[TMP_1]`, which is incorrect/imprecise currently.

Goal dataflow state after the IRs:
```
...
s[_] -may-> <storage N> // new <storage>
<storage N> initialization edges
REF_2 ---> <storage N>
...
```

I think we can add a "hint" (a property) on the `REF_2 -> s[TMP_1]` IR so that dataflow state can understand it is really a new object and assign a new `<storage>` to REF_2, instead of `s[_]`. Dataflow can also initialize the `<storage>` as well (using the `delete` semantics, maybe). In this solution, we don't really need a new IR operation.
The `push(x)` case adds another deep-copy assignment to `REF_2`, which should work correctly at this point.

2023-04-25 17:34 UTC, kevinclancy commented
We aren't going to gain any object sensitivity from allocating a new storage location for `push(x)`, but I agree that it should be done for uniformity.

The problem with calling this operation `Push` is that the name suggests it is the only operation needed for performing the push method. We could rename it to `Allocate` or `AllocateElement` and use it for both `push()` and `push(x)`. We could remove the intialization functionality from `state_machine.py`'s implementation of `Push`; instead, it only recursively allocates the tree without initializing fields. As you mentioned, in the case of `push()` we would perform a `Delete` operation on the result, and in the case of `push(x)` we would use `Assign` to assign the result to x. 

I think adding a property to `Index` is not as clear as adding a separate `AllocateElement` operation.

2023-04-25 18:23 UTC, duckki commented
The fewer instructions the better for the long run. It multiplies the new detector development costs. So, adding a new IR instruction is a last resort.

Replacing `REF_2 -> s[TMP_1]` operation with `REF_2 -> AllocateElement( s )` could work, but we can achieve the same thing with the added property keeping existing and new detectors unchanged. There is nothing wrong about the current IR sequence and analysis just needs more context to process it better. In fact, analysis could deduce without a flag. But, I prefer adding a flag in IR over that.

Alternatively, we may replace the whole `push` call with a single `PUSH` IR instruction. I think this one is justifiable, since it raises the abstraction level of IR.

2023-04-25 22:31 UTC, kevinclancy commented
I decided to move all of the push functionality into the `Push` operation.

2023-04-26 01:10 UTC, duckki requested changes
I got a question in the IR class. And it looks like the commit `0702ab24650c36a4e61635d7956c71f2fa66e722` has been cherry-picked in this branch. You will need to rebase the branch on the commit, again.
Otherwise, looks good.

2023-04-26 01:10 UTC, duckki commented on slither/slithir/operations/push.py
> +        return []
Shouldn't we return the `_elem` (if exists)?

2023-04-26 17:28 UTC, duckki approved these changes

2023-04-26 17:33 UTC, merged